import numpy as np

# LIDAR参数
LIDAR_RANGE = 40
LIDAR_ANGLE_STEP = 0.5 / 180 * np.pi  # 0.5度的角度增量

# 机器人参数
ROBOT_RADIUS = 8
STEP_SIZE = 12

# 探索参数
EXPLORATION_RATE_THRESHOLD = 0.95  # 探索率阈值
EXPLORATION_MAX_STEP = 200  # 最大步数

# PPO参数
LEARNING_RATE = 1e-4  # 从1e-4降到3e-5
GAMMA = 0.98  # 折扣因子
BATCH_SIZE = 32
TRAIN_EPOCHS = 5  # 从10降到5
ADVANTAGE_LAMBDA = 0.95
CLIP_EPSILON = 0.2  # GAE参数

# 训练参数
TRAIN_EPISODE_NUM = 1500  # 训练轮数
EVAL_INTERVAL = 10  # 评估间隔
SAVE_MODEL_INTERVAL = 200  # 保存模型间隔